# Sign worlds - a list of worlds where Welcome Warp Signs work. If this is blank, then they will work in all worlds. Worlds must be correctly capitalized.
# Example -
# signworlds:
# - survival
# - survival_nether

signworlds:
